### ISSUE TITLE
V2.13.0.0 inventory bug

### ISSUE THREAD

**Issue by LobsterX** [TheUnnamedOrganisation/RocketBot#10]
[00:24:28] () Backing up config.json to: D:\Users\xxxxx\Desktop\RocketBot2\config\config-27-1501691068394.backup.json
[00:24:28] () Migrating configuration from schema version 27 to 28
[00:24:28] () Validating config.json...
[00:24:30] () Backing up auth.json to: D:\Users\xxxxx\Desktop\RocketBot2\config\auth-27-1501691070407.backup.json
[00:24:30] () Migrating auth configuration from schema version 27 to 28
[00:24:30] () Validating Auth.json...
[00:24:35] () Key: xxxxXXXXXXXXXXXXxxxx RPM: 150 Expiration Date: 12/8/2017
[00:24:35] (INFO) Migrating accounts.db from schema version 27 to 28
[00:24:39] (BOT STATS) Account changed to xxxxxxxxxx
[00:24:39] (BOT STATS) xxxxxxxxxx | Lvl: 34 | XP:   173510 | SD:  1379472 | Runtime:   0 Min
[00:24:39] (BOT STATS) xxxxxxxxxx | Lvl: 30 | XP:   430689 | SD:   679144 | Runtime:   0 Min
[00:24:40] (INFO) You can find it at https://github.com/TheUnnamedOrganisation/RocketBot/releases
[00:24:40] (INFO) Your version is v2.13.0.0
[00:24:40] (UPDATE) GitHub version is 2.13.0.0
[00:24:45] (INFO) System.UnauthorizedAccessException: Access to the path 'D:\Users\xxxxx\Desktop\RocketBot2\RocketBot2.exe.old' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at RocketBot2.Logic.State.VersionCheckState.<CleanupOldFiles>d__5.MoveNext()
[00:24:46] (UPDATE) Perfect! You already have the newest Version 2.13.0.0
[00:24:46] (INFO) Logging in using Google xxxxxxxxxx
[00:24:46] (INFO) Your IP is: 119.74.252.206
[00:25:28] (INFO) Playing as MarcoOngWP
[00:25:29] (INFO) (HASH SERVER) Key[4U2LXXXXXXXXXXXX0W2X] Last Minute: 8 RPM, AVG: 1061.00 MS, Fastest: 1024, Slowest: 1115, Available: 68.00%, Expires: 08/13/2017 @ 13:12:10 PM (10 Days 12 Hours 46 Minutes)
[00:25:33] (ERROR) [Configuration Invalid] Your maximum items combined (Balls+Potions+Revives+Berries=374) is over your max item storage (350)
[00:25:33] (ATTENTION) Press any key to exit, then fix your config and run the bot again.

i have less then 350 items as of above logged records. recycling a further 100items did not solve the above. still can't run the bot as it keeps reporting i have more than my max storage

**Comment by LobsterX** [comment]
bad config migrating from "SchemaVersion": 27 to "SchemaVersion": 28. Config missing evolution filter

FIXED

**Comment by Furtif** [comment]
lol yeps is this 👍  sorry i have missed correct log
(Balls+Potions+Revives+Berries+Evolutions=374) i have 5 earch in config 

    ``{
      "Key": "itemDragonScale",
      "Value": 5
    },
    {
      "Key": "itemKingsRock",
      "Value": 5
    },
    {
      "Key": "itemSunStone",
      "Value": 5
    },
    {
      "Key": "itemMetalCoat",
      "Value": 5
    },
    {
      "Key": "itemUpGrade",
      "Value": 5
    }``

final result = total evolution items 25 
![unknown 1](https://user-images.githubusercontent.com/11375035/28885581-b1ccd080-77b6-11e7-9f9d-611ab23399cd.png)
