### ISSUE TITLE
cannot config multiple bots correctly

### ISSUE THREAD

**Issue by JingkunLi** [TheUnnamedOrganisation/RocketBot#50]
if there are 2 or more bots configed in "auth.json",  the setting window cannot be open.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at RocketBot2.Forms.SettingsForm..ctor(GlobalSettings& settings, ISession session, String[] _args)
   at RocketBot2.Forms.MainForm.<SettingsStripMenuItem_Click>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by Furtif** [comment]
Look this downolad the zip sample https://github.com/TheUnnamedOrganisation/RocketBot/issues/46

**Comment by joschioschi** [comment]
Think this happens when the multiple accounts in the auth.json do not fit to the definition in the accounts.db. The problem disappears when you delete the accounts.db. After this you can open the settings just as normal.
