### ISSUE TITLE
unstable

### ISSUE THREAD

**Issue by Bardockish** [TheUnnamedOrganisation/RocketBot#77]
[17:31:44] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[17:31:44] (ERROR) Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Newtonsoft.Json.Linq.JContainer.GetItem(Int32 index)
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)
   at PoGo.RocketBot.Logic.Navigation.Route(ISession session, GeoCoordinate start, GeoCoordinate dest) in c:\projects\rocketbot2\PoGo.RocketBot.Logic\Navigation.cs:line 212
   at PoGo.RocketBot.Logic.Navigation.<Move>d__14.MoveNext() in c:\projects\rocketbot2\PoGo.RocketBot.Logic\Navigation.cs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.RocketBot.Logic.Tasks.UseNearbyPokestopsTask.<WalkingToPokeStop>d__11.MoveNext() in c:\projects\rocketbot2\PoGo.RocketBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.RocketBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__9.MoveNext() in c:\projects\rocketbot2\PoGo.RocketBot.Logic\Tasks\UseNearbyPokestopsTask.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.RocketBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\rocketbot2\PoGo.RocketBot.Logic\Tasks\FarmPokestopsTask.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.RocketBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\rocketbot2\PoGo.RocketBot.Logic\State\FarmState.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.RocketBot.Logic.State.StateMachine.<Start>d__4.MoveNext() in c:\projects\rocketbot2\PoGo.RocketBot.Logic\State\StateMachine.cs:line 117

**Comment by Furtif** [comment]
Connection issues .... try later, listen to a lot of people who complained to it on the discord channels
